name: flutter_firebase_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:

  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.7

  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.1.0
  http: any
  provider: any
  flutter_native_splash: ^2.0.2
  flutter_map: ^0.14.0
  latlong2: ^0.8.0
  geocoding: ^2.0.2
  flutter_slidable: ^1.2.0
  image_picker: ^0.8.4+7

  flutter_lints: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
